dataset: jehan 
seed: 0 
model: resnet50 
epochs: 50 
project_name_suffix: __final_tasks_and_datasets_debug 
turn_off_scaler_normalization: True 
leftout_subject: 1
leave_one_subject_out: True 
transfer_learning: True 
cross_validation_for_time_series: True 
turn_on_rms: True 
save_images: True 
rms_input_windowsize: 10 
save_images: True 
turn_on_unlabeled_domain_adaptation: True 
unlabeled_algorithm: fixmatch 
finetuning_epochs: 750 
partial_dataset_ninapro: True 
pretrain_and_finetune: True 
proportion_transfer_learning: 0.5 
proportion_unlabeled_data: 0.5
