dataset: jehan
seed: 0
model: vit_tiny_patch2_32
epochs: 50
project_name_suffix: __jehan_unlabeled_study_v2 
turn_off_scaler_normalization: True
leftout_subject: 1
leave_one_subject_out: True
transfer_learning: True
cross_validation_for_time_series: True
turn_on_rms: True
save_images: True
rms_input_windowsize: 50
save_images: True
turn_on_unlabeled_domain_adaptation: True
unlabeled_algorithm: fixmatch
finetuning_epochs: 750
pretrain_and_finetune: False
proportion_transfer_learning: 0.0
proportion_unlabeled_data_from_leftout_subject: 0.0
proportion_data_from_training_subjects: 1.0
proportion_unlabeled_data_from_training_subjects: 0.8
learning_rate: 5e-4