starting_index: 1
ending_index: 10 # set to the maximum number of participants for the dataset
current_dataset: capgmyo # set to the dataset you want to run with
number_windows: 50 # set to 1/20 of sampling rate or 1/16 of sampling rate for Hyser
