dataset: $current_dataset 
seed: 0 
model: resnet18 
epochs: 100 
project_name_suffix: __preprocessing-comparison 
turn_off_scaler_normalization: True 
leftout_subject: $subj 
leave_one_subject_out: True 
transfer_learning: True
train_test_split_for_time_series: True 
save_images: True 
learning_rate: 5.0e-4 
proportion_transfer_learning: 0.2 
proportion_data_from_training_subjects: 1.0 
finetuning_epochs: 750 
pretrain_and_finetune: True 
partial_dataset_ninapro: True