dataset: jehan
seed: 42
model: resnet50
epochs: 50
project_name_suffix: __transfer-learning_debug
turn_off_scaler_normalization: True
leftout_subject: 1
leave_one_subject_out: True
turn_on_rms: True
transfer_learning: True
cross_validation_for_time_series: True
save_images: True
rms_input_windowsize: 50
turn_on_unlabeled_domain_adaptation: True
unlabeled_algorithm: fixmatch
learning_rate: 5e-4
proportion_transfer_learning: 0.5
# proportion_unlabeled_data_from_leftout_sub?ject: 0.0
# pretrain_and_finetune: True
proportion_data_from_training_subjects: 0.5
# proportion_unlabeled_data_from_training_subjects: 0.8
# finetuning_epochs: 750
# leave_one_session_out: True
# pretrain_and_finetune: True