dataset: jehan 
seed: 0 
model: resnet50 
epochs: 50 
project_name_suffix: __final_tasks_and_datasets_debug 
turn_off_scaler_normalization: True 
leftout_subject: 1
leave_one_subject_out: True 
turn_on_rms: True 
save_images: True 
rms_input_windowsize: 10 
partial_dataset_ninapro: True